### ISSUE TITLE
The stream has expired due to inactivity

### ISSUE THREAD

**Issue by juliuslipp** [libsql/go-libsql#12]
I'm only seeing after a certain amount of time. With the tursodatabase/libsql client, this does not happen.
```
error code = 1: Error executing statement: Hrana: `api error: `{"message":"The stream has expired due to inactivity","code":"STREAM_EXPIRED"}``
```

Any suggestions? One way to solve it, is to ping the db every few seconds.

**Comment by denisraison** [comment]
Hi @juliuslipp I see you closed it did you find a solution for it? Thanks :)

**Comment by juliuslipp** [comment]
@denisraison not really, ended up pinging the db every ~5 seconds.

**Comment by denisraison** [comment]
Haha I did the same here 🫠 thanks!
